package indicators



// 'Momentum Indicators': [
//         'ADX',
//         'ADXR',
//         'APO',
//         'AROON',
//         'AROONOSC',
//         'BOP',
//         'CCI',
//         'CMO',
//         'DX',
//         'MACD',
//         'MACDEXT',
//         'MACDFIX',
//         'MFI',
//         'MINUS_DI',
//         'MINUS_DM',
//         'MOM',
//         'PLUS_DI',
//         'PLUS_DM',
//         'PPO',
//         'ROC',
//         'ROCP',
//         'ROCR',
//         'ROCR100',
//         'RSI',
//         'STOCH',
//         'STOCHF',
//         'STOCHRSI',
//         'TRIX',
//         'ULTOSC',
//         'WILLR',
//         ],
